// Generated by CoffeeScript 1.9.3
(function() {
  var CND, IntervalTree, alert, badge, debug, echo, end, help, i, id, idx, info, itree, j, len, log, match, matches, probe, rpr, start, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'SCRATCH/cid-sets';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  IntervalTree = require('interval-tree2');

  itree = new IntervalTree(300);

  itree.add(0, 10);

  itree.add(5, 5.5);

  itree.add(3, 8);

  itree.add(4, 4.5);

  itree.add(6, 7);

  for (probe = i = -1; i <= 10; probe = ++i) {
    matches = itree.search(probe);
    if (!(matches.length > 0)) {
      warn(probe, "no matches");
      continue;
    }
    matches.sort(function(a, b) {
      if (a['id'] < b['id']) {
        return +1;
      }
      if (a['id'] > b['id']) {
        return -1;
      }
      return 0;
    });
    for (idx = j = 0, len = matches.length; j < len; idx = ++j) {
      match = matches[idx];
      start = match.start, end = match.end, id = match.id;
      (idx === 0 ? help : whisper)(probe, [start, end], rpr(id));
    }
  }

}).call(this);
